// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ZoneCreateConfig - Map containing zone configuration settings. See the section on specific zone types for details.
type ZoneCreateConfig struct {
	APIURL     *string `json:"apiUrl,omitempty"`
	Datacenter *string `json:"datacenter,omitempty"`
	Password   *string `json:"password,omitempty"`
	Username   *string `json:"username,omitempty"`
}

// ZoneCreateCredential - Map containing Credential ID. Setting `type` to `local` means use the values set in the local cloud config instead of associating a credential.
type ZoneCreateCredential struct {
	Type *string `json:"type,omitempty"`
}

// ZoneCreateVisibility - private or public
type ZoneCreateVisibility string

const (
	ZoneCreateVisibilityPrivate ZoneCreateVisibility = "private"
	ZoneCreateVisibilityPublic  ZoneCreateVisibility = "public"
)

func (e ZoneCreateVisibility) ToPointer() *ZoneCreateVisibility {
	return &e
}

func (e *ZoneCreateVisibility) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "private":
		fallthrough
	case "public":
		*e = ZoneCreateVisibility(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ZoneCreateVisibility: %v", v)
	}
}

// ZoneCreateZoneType - Map containing the Cloud (zone) code name. See the zone-types API to fetch a list of all available Cloud (zone) types and their codes.
type ZoneCreateZoneType struct {
	Code *string `json:"code,omitempty"`
}

type ZoneCreate struct {
	// Specifies which Tenant this cloud should be assigned to
	AccountID *int64 `json:"accountId,omitempty"`
	// Automatically Power on VMs
	AutoRecoverPowerState *bool `json:"autoRecoverPowerState,omitempty"`
	// Optional code for use with policies
	Code *string `json:"code,omitempty"`
	// Map containing zone configuration settings. See the section on specific zone types for details.
	Config *ZoneCreateConfig `json:"config,omitempty"`
	// Map containing Credential ID. Setting `type` to `local` means use the values set in the local cloud config instead of associating a credential.
	Credential *ZoneCreateCredential `json:"credential,omitempty"`
	// Optional description field if you want to put more info there
	Description *string `json:"description,omitempty"`
	// Can be used to disable the cloud
	Enabled *bool `json:"enabled,omitempty"`
	// Specifies which Server group this cloud should be assigned to
	GroupID int64 `json:"groupId"`
	// Linked Account ID (enter commercial ID to get costing for AWS Govcloud)
	LinkedAccountID *int64 `json:"linkedAccountId,omitempty"`
	// Optional location for your cloud
	Location *string `json:"location,omitempty"`
	// A unique name scoped to your account for the cloud
	Name string `json:"name"`
	// Scale Priority
	ScalePriority *int64 `json:"scalePriority,omitempty"`
	// host firewall. `off` or `internal`. a.k.a. "local firewall"
	SecurityMode *string `json:"securityMode,omitempty"`
	// private or public
	Visibility *ZoneCreateVisibility `json:"visibility,omitempty"`
	// Map containing the Cloud (zone) code name. See the zone-types API to fetch a list of all available Cloud (zone) types and their codes.
	ZoneType ZoneCreateZoneType `json:"zoneType"`
}
