// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ZoneCreateConfigNetworkServer struct {
	ID *string `json:"id,omitempty"`
}

type ZoneCreateConfig struct {
	EnableNetworkTypeSelection *string                        `json:"_enableNetworkTypeSelection,omitempty"`
	UseHostCredentials         *string                        `json:"_useHostCredentials,omitempty"`
	AccessKey                  *string                        `json:"accessKey,omitempty"`
	AccountType                *string                        `json:"accountType,omitempty"`
	APIURL                     *string                        `json:"apiUrl,omitempty"`
	APIVersion                 *string                        `json:"apiVersion,omitempty"`
	ApplianceURL               *string                        `json:"applianceUrl,omitempty"`
	AzureCostingMode           *string                        `json:"azureCostingMode,omitempty"`
	BackupMode                 *string                        `json:"backupMode,omitempty"`
	CertificateProvider        *string                        `json:"certificateProvider,omitempty"`
	ClientEmail                *string                        `json:"clientEmail,omitempty"`
	ClientID                   *string                        `json:"clientId,omitempty"`
	ClientSecret               *string                        `json:"clientSecret,omitempty"`
	ClientSecretHash           *string                        `json:"clientSecretHash,omitempty"`
	CloudType                  *string                        `json:"cloudType,omitempty"`
	Cluster                    *string                        `json:"cluster,omitempty"`
	ConfigCmID                 *string                        `json:"configCmId,omitempty"`
	ConfigCmdbDiscovery        *bool                          `json:"configCmdbDiscovery,omitempty"`
	ConfigCmdbID               *string                        `json:"configCmdbId,omitempty"`
	ConfigManagementID         *string                        `json:"configManagementId,omitempty"`
	CostingAccessKey           *string                        `json:"costingAccessKey,omitempty"`
	CostingBucket              *string                        `json:"costingBucket,omitempty"`
	CostingBucketName          *string                        `json:"costingBucketName,omitempty"`
	CostingFolder              *string                        `json:"costingFolder,omitempty"`
	CostingRegion              *string                        `json:"costingRegion,omitempty"`
	CostingReport              *string                        `json:"costingReport,omitempty"`
	CostingReportName          *string                        `json:"costingReportName,omitempty"`
	CostingSecretKey           *string                        `json:"costingSecretKey,omitempty"`
	CostingSecretKeyHash       *string                        `json:"costingSecretKeyHash,omitempty"`
	CspClientID                *string                        `json:"cspClientId,omitempty"`
	CspClientSecret            *string                        `json:"cspClientSecret,omitempty"`
	CspClientSecretHash        *string                        `json:"cspClientSecretHash,omitempty"`
	CspCustomer                *string                        `json:"cspCustomer,omitempty"`
	CspTenantID                *string                        `json:"cspTenantId,omitempty"`
	Datacenter                 *string                        `json:"datacenter,omitempty"`
	DatacenterID               *string                        `json:"datacenterId,omitempty"`
	DatacenterName             *string                        `json:"datacenterName,omitempty"`
	DiskEncryption             *string                        `json:"diskEncryption,omitempty"`
	DiskStorageType            *string                        `json:"diskStorageType,omitempty"`
	DistributedWorkerID        *string                        `json:"distributedWorkerId,omitempty"`
	DNSIntegrationID           *string                        `json:"dnsIntegrationId,omitempty"`
	EbsEncryption              *string                        `json:"ebsEncryption,omitempty"`
	EnableDiskTypeSelection    *string                        `json:"enableDiskTypeSelection,omitempty"`
	EnableVnc                  *string                        `json:"enableVnc,omitempty"`
	EncryptionSet              *string                        `json:"encryptionSet,omitempty"`
	Endpoint                   *string                        `json:"endpoint,omitempty"`
	GoogleRegionID             *string                        `json:"googleRegionId,omitempty"`
	HideHostSelection          *string                        `json:"hideHostSelection,omitempty"`
	ImageStoreID               *string                        `json:"imageStoreId,omitempty"`
	ImportExisting             *string                        `json:"importExisting,omitempty"`
	InventoryLevel             *string                        `json:"inventoryLevel,omitempty"`
	IsVpc                      *string                        `json:"isVpc,omitempty"`
	KubeURL                    *string                        `json:"kubeUrl,omitempty"`
	NetworkServer              *ZoneCreateConfigNetworkServer `json:"networkServer,omitempty"`
	NetworkServerID            *string                        `json:"networkServer.id,omitempty"`
	Password                   *string                        `json:"password,omitempty"`
	PasswordHash               *string                        `json:"passwordHash,omitempty"`
	PrivateKey                 *string                        `json:"privateKey,omitempty"`
	PrivateKeyHash             *string                        `json:"privateKeyHash,omitempty"`
	ProjectID                  *string                        `json:"projectId,omitempty"`
	ReplicationMode            *string                        `json:"replicationMode,omitempty"`
	ResourceGroup              *string                        `json:"resourceGroup,omitempty"`
	ResourcePool               *string                        `json:"resourcePool,omitempty"`
	ResourcePoolID             *string                        `json:"resourcePoolId,omitempty"`
	RPCMode                    *string                        `json:"rpcMode,omitempty"`
	SecretKey                  *string                        `json:"secretKey,omitempty"`
	SecretKeyHash              *string                        `json:"secretKeyHash,omitempty"`
	SecurityMode               *string                        `json:"securityMode,omitempty"`
	SecurityServer             *string                        `json:"securityServer,omitempty"`
	ServiceRegistryID          *string                        `json:"serviceRegistryId,omitempty"`
	StsAssumeRole              *string                        `json:"stsAssumeRole,omitempty"`
	SubscriberID               *string                        `json:"subscriberId,omitempty"`
	TenantID                   *string                        `json:"tenantId,omitempty"`
	Username                   *string                        `json:"username,omitempty"`
	Vpc                        *string                        `json:"vpc,omitempty"`
}

// ZoneCreateCredential - Map containing Credential ID. Setting `type` to `local` means use the values set in the local cloud config instead of associating a credential.
type ZoneCreateCredential struct {
	Type *string `json:"type,omitempty"`
}

// ZoneCreateVisibility - private or public
type ZoneCreateVisibility string

const (
	ZoneCreateVisibilityPrivate ZoneCreateVisibility = "private"
	ZoneCreateVisibilityPublic  ZoneCreateVisibility = "public"
)

func (e ZoneCreateVisibility) ToPointer() *ZoneCreateVisibility {
	return &e
}

func (e *ZoneCreateVisibility) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "private":
		fallthrough
	case "public":
		*e = ZoneCreateVisibility(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ZoneCreateVisibility: %v", v)
	}
}

// ZoneCreateZoneType - Map containing the Cloud (zone) code name. See the zone-types API to fetch a list of all available Cloud (zone) types and their codes.
type ZoneCreateZoneType struct {
	Code *string `json:"code,omitempty"`
}

type ZoneCreate struct {
	// Specifies which Tenant this cloud should be assigned to
	AccountID *int64 `json:"accountId,omitempty"`
	// Automatically Power on VMs
	AutoRecoverPowerState *bool `json:"autoRecoverPowerState,omitempty"`
	// Optional code for use with policies
	Code   *string           `json:"code,omitempty"`
	Config *ZoneCreateConfig `json:"config,omitempty"`
	// Map containing Credential ID. Setting `type` to `local` means use the values set in the local cloud config instead of associating a credential.
	Credential *ZoneCreateCredential `json:"credential,omitempty"`
	// Optional description field if you want to put more info there
	Description *string `json:"description,omitempty"`
	// Can be used to disable the cloud
	Enabled *bool `json:"enabled,omitempty"`
	// Specifies which Server group this cloud should be assigned to
	GroupID int64 `json:"groupId"`
	// Linked Account ID (enter commercial ID to get costing for AWS Govcloud)
	LinkedAccountID *int64 `json:"linkedAccountId,omitempty"`
	// Optional location for your cloud
	Location *string `json:"location,omitempty"`
	// A unique name scoped to your account for the cloud
	Name string `json:"name"`
	// Scale Priority
	ScalePriority *int64 `json:"scalePriority,omitempty"`
	// host firewall. `off` or `internal`. a.k.a. "local firewall"
	SecurityMode *string `json:"securityMode,omitempty"`
	// private or public
	Visibility *ZoneCreateVisibility `json:"visibility,omitempty"`
	// Map containing the Cloud (zone) code name. See the zone-types API to fetch a list of all available Cloud (zone) types and their codes.
	ZoneType ZoneCreateZoneType `json:"zoneType"`
}
