// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ZoneCredential struct {
	Type *string `json:"type,omitempty"`
}

type ZoneGroups struct {
	AccountID *int64  `json:"accountId,omitempty"`
	ID        *int64  `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
}

type Zone struct {
	AccountID     *int64             `json:"accountId,omitempty"`
	Code          *string            `json:"code,omitempty"`
	Config        *ZoneVcenterConfig `json:"config,omitempty"`
	Credential    *ZoneCredential    `json:"credential,omitempty"`
	Enabled       *bool              `json:"enabled,omitempty"`
	Groups        []ZoneGroups       `json:"groups,omitempty"`
	ID            *int64             `json:"id,omitempty"`
	Name          *string            `json:"name,omitempty"`
	ScalePriority *int64             `json:"scalePriority,omitempty"`
	Visibility    *string            `json:"visibility,omitempty"`
}
