// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"MyTest/internal/sdk/pkg/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *MaintResourceModel) RefreshFromCreateResponse(resp *shared.TwoHundredSuccess) {
	if resp.Success != nil {
		r.Success = types.BoolValue(*resp.Success)
	} else {
		r.Success = types.BoolNull()
	}
}
